from detectron2.config.defaults import _C
from detectron2.config import CfgNode


_C.MODEL.OCR = CfgNode()
_C.MODEL.OCR.ENABLED = False
_C.MODEL.OCR.NUM_NEARBY_TEXT_ENC = 5
_C.MODEL.OCR.ENCODING = CfgNode()
_C.MODEL.OCR.ENCODING.TYPE = "BagOfChar"
_C.MODEL.OCR.ENCODING.DECAY_FACTOR = 0.25
_C.MODEL.OCR.ENCODING.AMBIGUATE_DIGITS = True

_C.MODEL.ROI_HEADS.PARTIAL_LABEL_PROPOSAL_IOU_THRESHOLD = 0.25
_C.MODEL.ROI_HEADS.PARTIAL_LABEL_TRAIN_FREQ = 0.5
_C.MODEL.ROI_HEADS.PARTIAL_LABEL_PROP_MAX = 0.2
_C.MODEL.ROI_HEADS.NUM_FC_AFTER_PROP = 2
_C.MODEL.ROI_HEADS.FC_DIM = 256
_C.MODEL.ROI_HEADS.USE_OWN_ALT_INPUT = False
